services:
  - type: web
    name: annoying-pixel-bot
    runtime: python3.11
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TOKEN
        value: